config/routes.rb
Rails.application.routes.draw do
  scope '/:foodcoop' do
    post 'finance/group_order_invoice', to: 'group_order_invoices#create_multiple'
    resources :group_order_invoices
  end
end

app/models/group_order_invoice.rb
class GroupOrderInvoice < ApplicationRecord
  belongs_to :group_order
  validates_presence_of :group_order
  validates_uniqueness_of :invoice_number
  validate :tax_number_set
  after_initialize :init, unless: :persisted?

  def generate_invoice_number(count)
    trailing_number = count.to_s.rjust(4, '0')
    if GroupOrderInvoice.find_by(invoice_number: self.invoice_date.strftime("%Y%m%d") + trailing_number)
      generate_invoice_number(count.to_i + 1)
    else
      self.invoice_date.strftime("%Y%m%d") + trailing_number
    end
  end

  def tax_number_set
    if FoodsoftConfig[:contact][:tax_number].blank?
      errors.add(:group_order_invoice, "Keine Steuernummer in FoodsoftConfig :contact gesetzt")
    end
  end

  def init
    self.invoice_date = Time.now unless invoice_date
    self.invoice_number = generate_invoice_number(1) unless self.invoice_number
    self.payment_method = FoodsoftConfig[:group_order_invoices]&.[](:payment_method) || I18n.t('activerecord.attributes.group_order_invoice.payment_method') unless self.payment_method
  end

  def name
    I18n.t('activerecord.attributes.group_order_invoice.name') + "_#{invoice_number}"
  end

  def load_data_for_invoice
    invoice_data = {}
    order = group_order.order
    invoice_data[:supplier] = order.supplier.name
    invoice_data[:ordergroup] = group_order.ordergroup
    invoice_data[:group_order] = group_order
    invoice_data[:invoice_number] = invoice_number
    invoice_data[:invoice_date] = invoice_date
    invoice_data[:tax_number] = FoodsoftConfig[:contact][:tax_number]
    invoice_data[:payment_method] = payment_method
    invoice_data[:order_articles] = {}
    group_order.order_articles.each do |order_article|
      # Get the result of last time ordering, if possible
      goa = group_order.group_order_articles.detect { |tmp_goa| tmp_goa.order_article_id == order_article.id }

      # Build hash with relevant data
      invoice_data[:order_articles][order_article.id] = {
        :price => order_article.article.fc_price,
        :quantity => (goa ? goa.quantity : 0),
        :total_price => (goa ? goa.total_price : 0),
        :tax => order_article.article.tax
      }
    end
    invoice_data
  end
end

app/controllers/concerns/send_group_order_invoice_pdf.rb
module Concerns::SendGroupOrderInvoicePdf
  extend ActiveSupport::Concern

  protected

  def send_group_order_invoice_pdf(group_order_invoice)
    invoice_data = group_order_invoice.load_data_for_invoice
    invoice_data[:title] = t('documents.group_order_invoice_pdf.title', supplier: invoice_data[:supplier])
    invoice_data[:no_footer] = true
    pdf = GroupOrderInvoicePdf.new invoice_data
    send_data pdf.to_pdf, filename: pdf.filename, type: 'application/pdf'
  end
end

app/controllers/group_order_invoices_controller.rb
class GroupOrderInvoicesController < ApplicationController
  include Concerns::SendGroupOrderInvoicePdf
  before_action :authenticate_finance

  def show
    begin
      @group_order_invoice = GroupOrderInvoice.find(params[:id])
      if FoodsoftConfig[:contact][:tax_number]
        respond_to do |format|
          format.pdf do
            send_group_order_invoice_pdf @group_order_invoice if FoodsoftConfig[:contact][:tax_number]
          end
        end
      else
        raise RecordInvalid
      end
    rescue ActiveRecord::RecordInvalid => error
      redirect_back fallback_location: root_path, notice: 'Something went wrong', alert: I18n.t('errors.general_msg', msg: "#{error} " + I18n.t('errors.check_tax_number'))
    end
  end

  def destroy
    goi = GroupOrderInvoice.find(params[:id])
    @order = goi.group_order.order
    goi.destroy
    respond_to do |format|
      format.js
      format.json { head :no_content }
    end
  end

  def create_multiple
    invoice_date = params[:group_order_invoice][:invoice_date]
    order_id = params[:group_order_invoice][:order_id]
    @order = Order.find(order_id)
    gos = GroupOrder.where("order_id = ?", order_id)
    gos.each do |go|
      goi = GroupOrderInvoice.find_or_create_by!(group_order_id: go.id)
      goi.invoice_date = invoice_date
      goi.invoice_number = goi.generate_invoice_number(1)
      goi.save!
    end
    respond_to do |format|
      format.js
    end
  end

  def create
    go = GroupOrder.find(params[:group_order])
    @order = go.order
    GroupOrderInvoice.find_or_create_by!(group_order_id: go.id)
    respond_to do |format|
      format.js
    end
    redirect_back fallback_location: root_path
  rescue => error
    redirect_back fallback_location: root_path, notice: 'Something went wrong', :alert => I18n.t('errors.general_msg', :msg => error)
  end
end

app/views/group_order_invoices/_links.html.haml
.row
  .column.small-12
    - show_generate_with_date = true
    - order.group_orders.each do |go|
      - if go.group_order_invoice.present?
        - show_generate_with_date = false
    - if show_generate_with_date
      = form_for :group_order_invoice, url: url_for('group_order_invoice#create_multiple'), remote: true do |f| 
        = f.label :invoice_date, I18n.t('activerecord.attributes.group_order_invoice.links.invoice_date')
        = f.date_field :invoice_date, {value: Date.today, max: Date.today, required: true}
        = f.hidden_field :order_id, value: order.id
        = f.submit  I18n.t('activerecord.attributes.group_order_invoice.links.generate_with_date'), class: 'btn btn small'

- order.group_orders.includes([:group_order_invoice, :ordergroup]).each do |go|
  .row
    .column.small-3
      = label_tag go.ordergroup.name
    - if go.group_order_invoice
      .column.small-3
        = link_to I18n.t('activerecord.attributes.group_order_invoice.links.download'), group_order_invoice_path(go.group_order_invoice, :format => 'pdf'), class: 'btn btn-small'
      .column.small-3
        = link_to  I18n.t('activerecord.attributes.group_order_invoice.links.delete'), go.group_order_invoice, method: :delete, class: 'btn btn-danger btn-small', remote: true
    - else
      = button_to  I18n.t('activerecord.attributes.group_order_invoice.links.generate'), group_order_invoices_path(:method => :post, group_order: go) ,class: 'btn btn-small', params: {id: order.id}, remote: true

app/views/group_order_invoices/create.js.erb
$("#generate-invoice<%= params[:id] %>").html("<%= escape_javascript(render partial: 'links', locals: {order: @order}) %>");

app/views/group_order_invoices/create_multiple.js.erb
$("#generate-invoice<%= @order.id %>").html("<%= escape_javascript(render partial: 'links', locals: {order: @order}) %>");

app/views/group_order_invoices/destroy.js.erb
$("#generate-invoice<%= @order.id %>").html("<%= escape_javascript(render partial: 'links', locals: {order: @order}) %>");